In [1]:
import pandas as pd

In [2]:
df_employee = pd.read_csv('../../employeeEngagement/prep/employees.csv')

df_courseProgres = pd.read_csv('../../employeeEngagement/prep/courseProgress.csv')

In [3]:
df_courseProgres = df_courseProgres.drop_duplicates(subset=['employeeId'])

In [4]:

final_merge = pd.merge(
    df_employee, df_courseProgres,
    left_on=['id'],
    right_on=['employeeId'],
    how='inner'
)

In [5]:

final_merge = final_merge.groupby(['department']).size().reset_index(name="employee_count")

display(final_merge)

                             department  employee_count
0                     Business Analysis               6
1                       Cloud Computing               3
2                         Cybersecurity               4
3                          Data Science               6
4                Database USERistration               7
5                                DevOps               3
6               Enterprise Architecture               5
7          IT Compliance and Governance               2
8   Information Technology (IT) Support               6
9             Infrastructure Management               5
10                  Network Engineering               5
11                   Product Management               2
12                   Project Management               4
13               Quality Assurance (QA)               6
14       Research and Development (R&D)               3
15                 Software Development               3
16                Systems USERistration               9
17                    Technical Support               6
18             Training and Development               6
19          User Experience (UX) Design               4
20           User Interface (UI) Design               5